workflows:
    # ionic-capacitor-ios-app:
    #     name: Ionic Capacitor iOS App
    #     environment:
    #         vars:
    #             XCODE_WORKSPACE: "ios/App/App.xcworkspace" # <- 'App' is the default workspace name for Capacitor projects
    #             XCODE_SCHEME: "App" # <- 'App' is the default Scheme name for Capacitor projects
    #         node: latest
    #     scripts:
    #         - npm install     
    #         - npx cap sync
    #         - |
    #             # build iOS
    #             cd platforms/ios
    #             pod install
    #             xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    #     artifacts:
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    ionic-capacitor-android-app:
        name: Ionic Capacitor Android App
        environment:
          node: 16.13.1
        scripts:
          - export NODE_OPTIONS=--openssl-legacy-provider
          - npm i -g @ionic/cli
          - npm install @capacitor/core
          - npm install @capacitor/cli --save-dev
          - npm install
          - ionic capacitor build android --prod
          # - cd android
          # - ./gradlew assembleDebug
        artifacts:
          - android/app/build/outputs/**/*.apk