workflows:
    # ionic-capacitor-ios-app:
    #     name: Ionic Capacitor iOS App
    #     environment:
    #         vars:
    #             XCODE_WORKSPACE: "ios/App/App.xcworkspace" # <- 'App' is the default workspace name for Capacitor projects
    #             XCODE_SCHEME: "App" # <- 'App' is the default Scheme name for Capacitor projects
    #         node: latest
    #     scripts:
    #         - npm install     
    #         - npx cap sync
    #         - |
    #             # build iOS
    #             cd platforms/ios
    #             pod install
    #             xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    #     artifacts:
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    ionic-capacitor-android-app:
      triggering:
        events:
          - push
        cancel_previous_builds: true
      when:
        changeset:
          includes:
            - '/d'
      name: Ionic Capacitor Android App
      environment:
        node: 16.13.1
      scripts:
        - name: Set NODE_OPTIONS
          script: export NODE_OPTIONS=--openssl-legacy-provider

        - name: Install Ionic Client
          script: npm i -g @ionic/cli

        - name: Install capacitor
          script: |
            npm install @capacitor/core
            npm install @capacitor/cli --save-dev

        - name: NPM Install dependencies
          script: npm install

        - name: Capacitor Prepare BUILD
          script: ionic capacitor build android --prod --no-open

        - name: Set gradlew ejecutable
          working_directory: android
          script: chmod +x ./gradlew

        - name: Build Android APK
          working_directory: android
          script: ./gradlew assembleRelease
      artifacts:
        - android/app/build/outputs/**/*.apk
      publishing:
        email:
          recipients:
            - josloe@gmail.com