import { LISTADO_IMAGENES_COCHES } from "./imagenescoches";
import { IDataVehiculos } from "./vehiculosGeneral";
export const citroen: IDataVehiculos[] = [

    {
        "_id": "606651cbf59ae674f6c4727f1",
        "vehiculo": "citroenC1",
        "descripcion": "Citroen C1",
        "clasevehiculo": "a",
        "modelo": "Citroen C1",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4127JVH",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c4727f2",
        "vehiculo": "citroenC1",
        "descripcion": "Citroen C1",
        "clasevehiculo": "a",
        "modelo": "Citroen C1",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4765JFW",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c4727f3",
        "vehiculo": "citroenC1",
        "descripcion": "Citroen C1",
        "clasevehiculo": "a",
        "modelo": "Citroen C1",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "7800JLC",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c4727f4",
        "vehiculo": "citroenC1",
        "descripcion": "Citroen C1",
        "clasevehiculo": "a",
        "modelo": "Citroen C1",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "7808JLC",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c4727a5",
        "vehiculo": "citroenC1open",
        "descripcion": "Citroen C1 Open",
        "clasevehiculo": "b",
        "modelo": "Citroen C1 Open",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4598JSL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1open,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c472826",
        "vehiculo": "citroenC1Automatic",
        "descripcion": "Citroen C1 Auto",
        "clasevehiculo": "b",
        "modelo": "Citroen C1 Auto",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "a",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "7617JKK",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1Automatic,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c472827",
        "vehiculo": "citroenC1Automatic",
        "descripcion": "Citroen C1 Auto",
        "clasevehiculo": "b",
        "modelo": "Citroen C1 Auto",
        "pax": 4,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "a",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "2108JNK",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC1Automatic,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c472818",
        "vehiculo": "citroenC3",
        "descripcion": "Citroen C3",
        "clasevehiculo": "c",
        "modelo": "Citroen C3",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1103KFC",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC3,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c472819",
        "vehiculo": "citroenC3",
        "descripcion": "Citroen C3",
        "clasevehiculo": "c",
        "modelo": "Citroen C3",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1106KFC",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.citroenC3,
        "altImage": ""
    },


];


