import { LISTADO_IMAGENES_COCHES } from "./imagenescoches";
import { IDataVehiculos } from "./vehiculosGeneral";
export const peugeot: IDataVehiculos[] = [

    {
        "_id": "60da01aeac951t0bf3e7327962111a11",
        "vehiculo": "peugeot108",
        "descripcion": "Peugeot 108",
        "clasevehiculo": "a",
        "modelo": "Peugeot 108",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "9494JKK",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot108,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279422",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1194JBL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279423",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1435JBL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279424",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "6420JHT",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279425",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "7240JBR",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279426",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "8663JGW",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279427",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "9809JBK",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
];







