import { LISTADO_IMAGENES_COCHES } from "./imagenescoches";
import { IDataVehiculos } from "./vehiculosGeneral";
export const peugeot: IDataVehiculos[] = [

    {
        "_id": "60da00ceaa9590bf3e7527961",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4350DYF",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e7327962",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4387DYF",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01ceaa9590bf3e7327963",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4448DYF",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01ceaa9w590bf3e7327964",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4491DYF",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac951f0bf3e7327965",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "4001DYV",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01amac9510bf3e7327966",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "2306DYY",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aelc9510bf3e7327967",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "8941DZR",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da0a1aeac9510bf3e7327968",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "8958DZR",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01baeac9510bf3e7327969",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "3910DZW",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9q510bf3e73279610",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "9712FCG",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "6a0da01aeac9510bf3e73279611",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "0013FCH",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac951o0bf3e73279612",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "0147FCH",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac951b0bf3e73279613",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1482FCT",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60dqa01aeac9510bf3ek73279614",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1749FCT",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9s510bf3e73279615",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1900FCT",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9a510bf3e73279616",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "6659FDN",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60daa01aeac9510bf3e73279617",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "6767FDN",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9510bnf3e73279618",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "6854FDN",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9510bf3ek73279619",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "3810FFM",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac9510bf3ei73279620",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "5054DTV",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac951t0bf3e73279621",
        "vehiculo": "peugeot107",
        "descripcion": "Peugeot 107",
        "clasevehiculo": "a",
        "modelo": "Peugeot 107",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "5101DTV",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot107,
        "altImage": ""
    },
    {
        "_id": "60da01aeac951t0bf3e7327962111a11",
        "vehiculo": "peugeot108",
        "descripcion": "Peugeot 108",
        "clasevehiculo": "a",
        "modelo": "Peugeot 108",
        "pax": 5,
        "puertas": 2,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "9494JKK",
        "precio": 100,
        "srcImage": "", //LISTADO_IMAGENES_COCHES.peugeot108,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279422",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1194JBL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279423",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "1435JBL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279424",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "6420JHT",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279425",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "7240JBR",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279426",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "8663JGW",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
    {
        "_id": "60da00ceaa9590bf3e75279427",
        "vehiculo": "peugeot208",
        "descripcion": "Peugeot 208",
        "clasevehiculo": "c",
        "modelo": "Peugeot 208",
        "pax": 5,
        "puertas": 4,
        "conbustible": "95 oct",
        "transmision": "M",
        "topCase": 0,
        "aireacondicionado": true,
        "franquicia": 0,
        "entregado": false,
        "devuelto": false,
        "matricula": "9809JBK",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.peugeot208,
        "altImage": ""
    },
];







