import { LISTADO_IMAGENES_COCHES } from "./imagenescoches";
import { IDataCoches } from "./coches";


export const piaggios: IDataCoches[] = [
    {
        "_id": "606651cbf59ae674f6c472801",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "5337KGB",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472802",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "2558KGB",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472803",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "7844JZP",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472804",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "9022JYY",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472805",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "9019JYY",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472806",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "5669JYZ",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472807",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "0582JYZ",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472808",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "9292JYY",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c472809",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "5480JYZ",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c4728010",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "7984JZP",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c4728011",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "8454JZP",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    },{
        "_id": "606651cbf59ae674f6c4728012",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "2495KGB",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c4728013",
        "vehiculo": "piaggioLiberty125",
        "descripcion": "Piaggio Liberty 125",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "0928JYZ",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggioLiberty125,
        "altImage": ""
    },


    {
        "_id": "606651cbf59ae674f6c4728014",
        "vehiculo": "piaggiomedley",
        "descripcion": "Piaggio Medley",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "0496KJL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggiomedley,
        "altImage": ""
    },
    {
        "_id": "606651cbf59ae674f6c4728015",
        "vehiculo": "piaggiomedley",
        "descripcion": "Piaggio Medley",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "7538LBN",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggiomedley,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c4728016",
        "vehiculo": "piaggiomedley",
        "descripcion": "Piaggio Medley",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "0555KJL",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggiomedley,
        "altImage": ""
    }, {
        "_id": "606651cbf59ae674f6c4728017",
        "vehiculo": "piaggiomedley",
        "descripcion": "Piaggio Medley",
        "clasevehiculo": "motos1",
        "modelo": "125",
        "pax": 2,
        "puertas": 0,
        "conbustible": "95 oct",
        "transmision": "A",
        "topCase": 1,
        "aireacondicionado": false,
        "franquicia": 150,
        "entregado": false,
        "devuelto": false,
        "matricula": "6664KTN",
        "precio": 100,
        "srcImage": LISTADO_IMAGENES_COCHES.piaggiomedley,
        "altImage": ""
    },
];






