import { LISTADO_IMAGENES_COCHES } from "./imagenescoches";
import { IDataVehiculos } from "./vehiculosGeneral";
export const suzukis: IDataVehiculos[] = [

{
"_id": "606651cbf59ae674f6c472791",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "0847JNW",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""


},
{
"_id": "606651cbf59ae674f6c472792",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "5001JNR",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472793",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "2349JGV",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472794",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "8595JNS",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472795",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "7215JYY",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472796",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "0848JNW",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472797",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "0065JLD",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},
{
"_id": "606651cbf59ae674f6c472798",
"vehiculo": "suzukyBurgman125",
"descripcion": "Suzuky Burgman 125",
"clasevehiculo": "m",
"modelo":  "Suzuky Burgman 125",
"pax": 2,
"puertas": 0,
"conbustible": "95 oct",
"transmision": "A",
"topCase": 1,
"aireacondicionado": false,
"franquicia": 150,
"entregado": false,
"devuelto": false,
"matricula": "0237JSV",
"precio": 100,
"srcImage": LISTADO_IMAGENES_COCHES.suzukyBurgman125,
"altImage": ""
},

];