name: Build For Android
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Building APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install Ionic
        run: |
          npm install -g @ionic/cli
          npm install @capacitor/core
          npm install @capacitor/cli --save-dev

      - name: Install app dependencies
        run: npm install

      - name: Build Android Release APK
        run: ionic capacitor build android --prod --no-open

      - name: Make gradlew executable
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Build the app
        working-directory: ./android
        run: ./gradlew build --no-daemon

      - name: Sign Android build
        run: jarsigner -keystore src/keystorefile.jks -storepass kleptor123 -keypass kleptor123 android/app/build/outputs/apk/release/app-release-unsigned.apk key0
      #   run: keytool -genkey -v -keystore debug.keystore -storepass kleptor123 -alias key0 -keypass kleptor123 -keyalg RSA -keysize 2048 -validity 10000
      - name: Prepare to sign build
        run: mv ./android/app/build/outputs/apk/release/app-release-unsigned.apk ./android/app/build/outputs/apk/release/release.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./android/app/build/outputs/apk/release/release.apk
          asset_name: release.apk
          tag: ${{ github.ref }}
          overwrite: true
          body: "Nueva version"
  
