name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'


        # uses: actions/setup-java@v1
        # with:
          # java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install Ionic
        run: |
          npm install -g @ionic/cli
          npm install @capacitor/core
          npm install @capacitor/cli --save-dev

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        # run: ionic build
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync
        # run: ionic capacitor sync --prod

      # - name: Build Android Dev APK
      #   run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --prod --no-open

      - name: Make gradlew executable
        working-directory: ./android/
        run: chmod +x ./gradlew

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew assembleRelease

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: apk/app-debug.apk

      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release
      #     path: apk/app.aab